# For more information on how to use this pipeline please refer to:
# http://tardis-sn.github.io/tardis/development/continuous_integration.html

name: sync-mirror

on:
  push:
    branches:
      - master

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Clone mirror repository
        run: |
          git clone --bare https://tardis-sn@dev.azure.com/tardis-sn/TARDIS/_git/tardis-refdata

      - name: Set upstream remote
        run: |
          cd tardis-refdata.git
          git remote add --mirror=fetch upstream https://github.com/tardis-sn/tardis-refdata.git
          git fetch upstream --tags

      - name: Fetch LFS objects
        run: |
          cd tardis-refdata.git 
          git lfs fetch upstream --all

      - name: Push changes to mirror
        run: |
          cd tardis-refdata.git
          MY_PAT=${{ secrets.AZURE_TOKEN }}
          B64_PAT=$(printf ":$MY_PAT" | base64)
          git -c http.extraHeader="Authorization: Basic ${B64_PAT}" push origin --all
